name: "Build and Deploy to Cloud Run"

on:
  push:
    branches:
      - "main"

env:
  PROJECT_ID: "vast-formula-48020-a1" # TODO: update to your Google Cloud project ID
  REGION: "us-central1" # TODO: update to your region
  SERVICE: "tfm-test" # TODO: update to your service name
  WORKLOAD_IDENTITY_PROVIDER: "projects/725722089/locations/global/workloadIdentityPools/github/providers/github-actions-provider" # TODO: update to your workload identity provider
  SERVICE_ACCOUNT: "the-last-mile-admin@vast-formula-478020-a1.iam.gserviceaccount.com"


jobs:
  deploy:
    runs-on: "ubuntu-latest"


    permissions:
      contents: "read"
      id-token: "write"


    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"


      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "${{ env.WORKLOAD_IDENTITY_PROVIDER }}"
          service_account: "${{ env.SERVICE_ACCOUNT }}"


      - name: "Docker Auth"
        run: |
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin ${{ env.REGION }}-docker.pkg.dev


      - name: "Build and Push Container"
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/search-agent:${{ github.sha }}"
          docker build --tag "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"


      - name: "Deploy to Cloud Run"
        uses: "google-github-actions/deploy-cloudrun@v2"
        with:
          service: "${{ env.SERVICE }}"
          region: "${{ env.REGION }}"
          image: "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/search-agent:${{ github.sha }}"
          flags: "--allow-unauthenticated --port=8000 --set-env-vars=JWT_SECRET=GOOGLE_CLOUD_PROJECT=${{ env.PROJECT_ID }},GOOGLE_CLOUD_LOCATION=${{ env.REGION }}"


      - name: "Show output"
        run: |
          echo ${{ steps.deploy.outputs.url }}
