name: "Build and Deploy to Cloud Run"

on:
  push:
    branches:
      - "main"

env:
  PROJECT_ID: "vast-formula-478020-a1"
  REGION: "us-central1"
  SERVICE: "cloudrun-service-tfm"
  WORKLOAD_IDENTITY_PROVIDER: "projects/725722089/locations/global/workloadIdentityPools/github/providers/github-actions-provider"
  SERVICE_ACCOUNT: "tlm-deploy-sa@vast-formula-478020-a1.iam.gserviceaccount.com"
  CSQL_INSTANCE : "tfm-db"

jobs:
  deploy:
    runs-on: "ubuntu-latest"


    permissions:
      contents: "read"
      id-token: "write"


    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"


      - id: "google_auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v3"
        with:
          workload_identity_provider: "${{ env.WORKLOAD_IDENTITY_PROVIDER }}"
          service_account: "${{ env.SERVICE_ACCOUNT }}"


      - id: "docker_auth"
        name: "Docker Auth"
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet


      - id: "build_and_push"
        name: "Build and Push Container"
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/server:${{ github.sha }}"
          docker build --tag "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"


      - id: "deploy"
        name: "Deploy to Cloud Run"
        uses: "google-github-actions/deploy-cloudrun@v3"
        with:
          service: "${{ env.SERVICE }}"
          region: "${{ env.REGION }}"
          image: "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/server:${{ github.sha }}"
          flags: "--allow-unauthenticated --port=8000 --add-cloudsql-instances=${{ env.PROJECT_ID }}:${{ env.REGION }}:${{ env.CSQL_INSTANCE }}"
          env_vars: |
            GOOGLE_CLOUD_PROJECT=${{ env.PROJECT_ID }},
            PUBSUB_TOPIC=file-processing-topic


      - name: "Show output"
        run: |
          echo ${{ steps.deploy.outputs.url }}
